### ISSUE TITLE
MemoryError: std::bad_alloc: cudaErrorMemoryAllocation: out of memory

### ISSUE THREAD

**Issue by 3019234115** [microsoft/Swin3D#15]
when I use 2GPU to train the s3ds segmentation it errs:
Traceback (most recent call last):                                                                                                          
  File "train.py", line 919, in <module>                                                                                                    
    main()
  File "train.py", line 114, in main
    mp.spawn(
  File "/home/lthpc/.conda/envs/Swin3d/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/lthpc/.conda/envs/Swin3d/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/lthpc/.conda/envs/Swin3d/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid) 
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/lthpc/.conda/envs/Swin3d/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/data/zhangqi/HZ/Swin3D_Task-main/SemanticSeg/train.py", line 514, in main_worker
    loss_train, mIoU_train, mAcc_train, allAcc_train = train(
  File "/data/zhangqi/HZ/Swin3D_Task-main/SemanticSeg/train.py", line 609, in train
    output = model(feat, coord, batch)
  File "/home/lthpc/.conda/envs/Swin3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lthpc/.conda/envs/Swin3d/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/lthpc/.conda/envs/Swin3d/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  File "/home/lthpc/.conda/envs/Swin3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/zhangqi/HZ/Swin3D_Task-main/SemanticSeg/model/Swin3D_RGB.py", line 70, in forward
    return self.backbone(sp, coords_sp)
  File "/home/lthpc/.conda/envs/Swin3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl    return forward_call(*input, **kwargs)
  File "/home/lthpc/.conda/envs/Swin3d/lib/python3.8/site-packages/Swin3D-0.0.0-py3.8-linux-x86_64.egg/Swin3D/models/Swin3D.py", line 132, in forward
    sp = self.stem_layer(sp)
  File "/home/lthpc/.conda/envs/Swin3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lthpc/.conda/envs/Swin3d/lib/python3.8/site-packages/Swin3D-0.0.0-py3.8-linux-x86_64.egg/Swin3D/modules/mink_layers.py", line 77, in forward
    x = self.conv_layers(x)
  File "/home/lthpc/.conda/envs/Swin3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lthpc/.conda/envs/Swin3d/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/lthpc/.conda/envs/Swin3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lthpc/.conda/envs/Swin3d/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/MinkowskiConvolution.py", line 314, in forward
    outfeat = self.conv.apply(
  File "/home/lthpc/.conda/envs/Swin3d/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/MinkowskiConvolution.py", line 72, in forward
    return fw_fn(
MemoryError: std::bad_alloc: cudaErrorMemoryAllocation: out of memory

Does anyone know how to fix it?
I can use singe GPU to train now by setting train_gpu to [0] in Swin3D_Task-main/SemanticSeg/config/s3dis/swin3D_RGB_L.yaml

**Comment by Yukichiii** [comment]
Could you please share your config files of your single GPU and 2GPU training? And how much memory does the GPU you're using have?

**Comment by 3019234115** [comment]
I have fixed the problem, it seems to be my computer server problems.  When I rerun the code , it works well.
Thank you for answering!
But I have another question: The paper said the experiments on s3ds are pretrained for 600 epoches with batch size 12, but the code is pretrained for 100 epoches with batch size 3, does it matters if I want to get the best result and do several extra experiment based on swin3d.

**Comment by Yukichiii** [comment]
Sorry that the default s3dis config is used for debug the released code.
Our finetuning experimental setup is consistent with the article, the batchsize is 12 and epoch number is 600.

**Comment by Yukichiii** [comment]
Sorry that the default s3dis config is used for debugging the released code.
Our finetuning experimental setup is consistent with the paper, the `batch_size` is set to 12 and the epoch number is 600.
When training from scratch, the batch_size is the same but the epoch number is 3000.

**Comment by mooncakehub** [comment]
How many GPU memory are needed in this network? Can you describe how to use two gpus to training. Thank you!
